EMBEDDING="nomic-embed-text"
COLLECTION="tuh_eeg_chunked_64"
LLM="openai"
DOMAIN="patients"

python rag/search.py -em ${EMBEDDING} -c ${COLLECTION} -l ${LLM} -d ${DOMAIN} -s "PLED, GPED, IED, interictal epileptiform discharges" -n 40 -ov 250 -ds cosine -rr -q "What are the common clinical symptoms of patients displaying interictal epileptiform discharges?"
python rag/search.py -em ${EMBEDDING} -c ${COLLECTION} -l ${LLM} -d ${DOMAIN} -s "PDA, polymorphic delta activity" -n 40 -ov 250 -ds cosine -rr -q "What are the common clinical symptoms of patients displaying polymorphic delta activity?"
python rag/search.py -em ${EMBEDDING} -c ${COLLECTION} -l ${LLM} -d ${DOMAIN} -s "history of drug abuse" -n 40 -ov 250 -ds cosine -rr -q "Are there any common complaints seen in patients with a history of drug abuse?"
python rag/search.py -em ${EMBEDDING} -c ${COLLECTION} -l ${LLM} -d ${DOMAIN} -s "focal slowing" -n 40 -ov 250 -ds cosine -rr -q "What are the common clinical symptoms of patients displaying focal slowing?"
python rag/search.py -em ${EMBEDDING} -c ${COLLECTION} -l ${LLM} -d ${DOMAIN} -s "diffuse slowing" -n 40 -ov 250 -ds cosine -rr -q "What are the common clinical symptoms of patients displaying diffuse slowing?"
python rag/search.py -em ${EMBEDDING} -c ${COLLECTION} -l ${LLM} -d ${DOMAIN} -s "diabetes" -n 40 -ov 250 -ds cosine -rr -q "Do we see any effects from diabetes on the EEG?"
python rag/search.py -em ${EMBEDDING} -c ${COLLECTION} -l ${LLM} -d ${DOMAIN} -s "FIRDA, TIRDA, IRDA, intermittent rhythmic delta activity" -n 40 -ov 250 -ds cosine -rr -q "What are the common clinical symptoms of patients displaying intermittent rhythmic delta activity?"
python rag/search.py -em ${EMBEDDING} -c ${COLLECTION} -l ${LLM} -d ${DOMAIN} -s "drug overdose" -n 40 -ov 250 -ds cosine -rr -q "Are there any common EEG patterns that accompany a drug overdose?"
python rag/search.py -em ${EMBEDDING} -c ${COLLECTION} -l ${LLM} -d ${DOMAIN} -s "alcohol withdrawl" -n 40 -ov 250 -ds cosine -rr -q "Are there any common EEG patterns that accompany alcohol withdrawl?"
